In [1]:
import torch

In [2]:
x = torch.linspace(0,2,2000)
x

tensor([0.0000e+00, 1.0005e-03, 2.0010e-03,  ..., 1.9980e+00, 1.9990e+00,
        2.0000e+00])

In [3]:
y = 2.3 + 3.12*(x)+3*(x**2)+6.98*(x**3)
y

tensor([ 2.3000,  2.3031,  2.3063,  ..., 76.1823, 76.2811, 76.3800])

In [4]:
a,b,c,d = torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True)
a,b,c,d

(tensor([-0.6197], requires_grad=True),
 tensor([-0.2549], requires_grad=True),
 tensor([0.1743], requires_grad=True),
 tensor([0.2304], requires_grad=True))

In [5]:
lr = 0.0000001
for i in range(1000):
  y_pred = a+b*(x)+c*(x**2)+d*(x**3)
  loss = (y_pred-y).pow(2).sum()
  if i%100==0:
    print(i,loss.item())
  loss.backward()

  with torch.no_grad(): #to avoid building derivation tree again and again for each variable
    a-=lr*a.grad
    b-=lr*b.grad
    c-=lr*c.grad
    d-=lr*d.grad

    a.grad = None
    b.grad = None
    c.grad = None
    d.grad = None




print(f'y = {a.item()}+{b.item()}x+{c.item()}x^2+{d.item()}x^3')

0 1949190.75
100 636365.375
200 208669.484375
300 69288.25
400 23822.751953125
500 8951.3720703125
600 4048.458984375
700 2395.5390625
800 1804.0736083984375
900 1561.034423828125
y = 1.2672640085220337+2.3045458793640137x+4.157716751098633x^2+6.805000305175781x^3
