In [1]:
import torch

In [2]:
x = torch.linspace(0,2,2000)
x

tensor([0.0000e+00, 1.0005e-03, 2.0010e-03,  ..., 1.9980e+00, 1.9990e+00,
        2.0000e+00])

In [3]:
y = 2.3 + 3.12*(x)+3*(x**2)+6.98*(x**3)
y

tensor([ 2.3000,  2.3031,  2.3063,  ..., 76.1823, 76.2811, 76.3800])

In [4]:
a,b,c,d = torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True),torch.randn((1),requires_grad=True)
a,b,c,d

(tensor([0.9798], requires_grad=True),
 tensor([0.3664], requires_grad=True),
 tensor([-1.0855], requires_grad=True),
 tensor([1.7085], requires_grad=True))

In [5]:
optimizer = torch.optim.SGD([a,b,c,d],lr=0.0000001)

In [6]:
for i in range(1000):
  y_pred = a+b*(x)+c*(x**2)+d*(x**3)
  loss = (y_pred-y).pow(2).sum()
  if i%100==0:
    print(i,loss.item())

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

print(f'y = {a.item()}+{b.item()}x+{c.item()}x^2+{d.item()}x^3')


0 1474306.25
100 480433.6875
200 156694.046875
300 51236.09375
400 16878.50390625
500 5680.66943359375
600 2026.9256591796875
700 830.8090209960938
800 435.4817199707031
900 301.2902526855469
y = 2.4659018516540527+2.548074722290039x+2.384286642074585x^2+7.481374263763428x^3
